= Local developer setup

A local developer setup can easily be set up. Just ensure that you installed the xref:pre-reqs.adoc[].

== Start the required services

You can start Kafka, Keycloak, and PostgreSQL in a local developer mode using:

[source,shell]
----
podman-compose -f develop/compose.yaml up
----

You will need to provide a configuration. Currently, the easiest way is to create a `.env` file in the `server`
directory before starting the process. The following file is an example, which should work out of the box:

[source,shell]
----
include::attachment$dotenv.sh[]
----
<1> Enable/disable the injector module.
<2> The shared group ID, used when consuming events. If your environment doesn't support `USER` and `HOSTNAME`, you
need to provide a unique ID here yourself.
<3> Points to the public Drogue Cloud sandbox.
<4> Consumes from the publicly available `drogue-public-temperature` application.
<5> Uncomment to enable tracing with Jaeger. Can be used combination with the `develop/compose-health.yaml` deployment.

== Run the local server

[source,shell]
----
cd server
cargo run
----

TIP: If you use the link:https://book.drogue.io/drogue-cloud/dev/admin-guide/bare-metal.html[Drogue Cloud Server] single binary instead of the sandbox, you can re-use the Kafka, Keycloak and PostgreSQL services.
