= Drogue Doppelgänger

The Drogue IoT Doppelgänger project provides a digital twin implementation.

[quote, Wikipedia, Digital twin]
A *digital twin* is a virtual representation of a real-world physical system or product (a _physical twin_) that serves as the indistinguishable digital counterpart of it for practical purposes, such as system simulation, integration, testing, monitoring, and maintenance

[NOTE]
.Work in progress
--
This project is in its early stages. We do provide releases, in order to make it easier to try it out and adopt it.

However, we encourage you to give it a try, and provide feedback, or contribute in other ways. Every contribution is
welcome.
--

== The basics

In order to work with Doppelgaenger, it is recommended to get a basic understanding of the xref:concepts.adoc[]. If
you are interested into the system itself, take a look at the xref:architecture.adoc[].

== More advanced

We also have a xref:developer-guide:index.adoc[], which explains the inner workings in more detail.
