apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: doppelgaenger-input
spec:
  output:
    to:
      kind: ImageStreamTag
      name: doppelgaenger-input:latest
  source:
    git:
      ref: main
      uri: https://github.com/drogue-iot/drogue-doppelgaenger
    contextDir: doppelgaenger-input
  strategy:
    dockerStrategy: {}
  triggers:
    - type: ConfigChange
