{
 "title": "summit2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Burrboards devices seen",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_burrboard_devices" }
   ]
  },
  {
   "title": "Total burrboard events processed by drogue cloud",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "burrboard_temperature_count" }
   ]
  },
  {
   "title": "Average system latency, last minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(burrboard_event_delta_sum[1m])/rate(burrboard_event_delta_count[1m]))*1000"
    }
   ]
  },
  {
   "title": "Buttons Hits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Buttons A total presses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "burrboard_buttons_a_presses" }
   ]
  },
  {
   "title": "Buttons B total presses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "burrboard_buttons_b_presses" }
   ]
  },
  {
   "title": "Last 30 seconds (both buttons combined)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(burrboard_buttons_a_presses + burrboard_buttons_b_presses )"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Light Average value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burrboard_light_sum/burrboard_light_count",
     "legendFormat": "Average light"
    },
    {
     "expr": "rate(burrboard_light_sum[5m])/rate(burrboard_light_count[5m])",
     "legendFormat": "Average light - last 5m"
    }
   ]
  },
  {
   "title": "Temperature Average value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burrboard_temperature_sum/burrboard_temperature_count",
     "legendFormat": "Average temperature"
    },
    {
     "expr": "rate(burrboard_temperature_sum[5m])/rate(burrboard_temperature_count[5m])",
     "legendFormat": "Average temperature - last 5m"
    }
   ]
  },
  {
   "title": "Average battery over the last 5 minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(burrboard_battery_sum[1m])/rate(burrboard_battery_count[1m])"
    }
   ]
  }
 ]
}