version: "3.9"
services:

  postgres:
    image: docker.io/bitnami/postgresql:14
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123456
      - POSTGRESQL_DATABASE=drogue
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: docker.io/moeenz/docker-kafka-kraft:latest
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=localhost
