
# Ports might seem a bit off, but they must be in the range of 30000-32767

global:
  drogueCloud:
    keycloak:
      insecure: true

drogueCloudTwin:

  api:
    ingress:
      insecure: true
      port: 80
    service:
      insecure: true

  services:

    backend:
      service:
        insecure: true

    debugger:
      ingress:
        insecure: true
        port: 80

    sso:
      ingress:
        insecure: true
        port: 80

    swaggerUi:
      ingress:
        insecure: true
        port: 80
      service:
        insecure: true
