name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  # Also on PRs, just be careful not to publish anything
  pull_request:
  workflow_dispatch:
    inputs:
      aarch64:
        type: boolean
        description: Build for aarch64
        required: false

env:
  VERSION_HELM: "v3.10.1"
  CONTAINER: podman

jobs:

  prepare:
    runs-on: ubuntu-22.04

    outputs:
      do-build: ${{steps.changed-files-irrelevant.outputs.only_modified != 'true' || steps.state.outputs.release == 'true'}}
      do-publish: ${{steps.state.outputs.do-publish}}
      release: ${{steps.state.outputs.release}}
      version: ${{steps.version.outputs.version}}
      prerelease: ${{steps.state.outputs.prerelease}}

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # Gather information for build

      - name: Evaluate state
        id: state
        run: |
          test -z "${{github.head_ref}}" && (echo 'do-publish=true' >> $GITHUB_OUTPUT)
          if [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "release=true" >> $GITHUB_OUTPUT
              echo "prerelease=false" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.ref }}" =~ ^refs/tags/v.*$ ]]; then
              echo "release=true" >> $GITHUB_OUTPUT
              echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Set version
        if: ${{github.head_ref == ''}}
        id: version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # evaluate changed files
      - name: Evaluate non-relevant changed files
        id: changed-files-irrelevant
        uses: tj-actions/changed-files@v34
        with:
          files: |
            docs/**

  info:
    name: info
    runs-on: ubuntu-22.04
    needs: [ prepare ]
    steps:
      - run: |
          echo "do-build: ${{needs.prepare.outputs.do-build}}"
          echo "do-publish: ${{needs.prepare.outputs.do-publish}}"
          echo "release: ${{needs.prepare.outputs.release}}"
          echo "version: ${{needs.prepare.outputs.version}}"
          echo "prerelease: ${{needs.prepare.outputs.prerelease}}"
          echo "aarch64: ${{github.event.inputs.aarch64}}"

  check:
    runs-on: ubuntu-22.04
    needs: [ prepare ]
    if: needs.prepare.outputs.do-build == 'true'
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .cargo-container-home
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential curl tzdata libssl-dev pkg-config libsasl2-dev librdkafka-dev libpq-dev libpqxx-dev

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check
        run: cargo check --release

  test:
    name: test
    runs-on: ubuntu-22.04
    needs: [ prepare, check ]
    if: needs.prepare.outputs.do-build == 'true'
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .cargo-container-home
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential curl tzdata libssl-dev pkg-config libsasl2-dev librdkafka-dev libpq-dev libpqxx-dev

      - name: Run tests
        env:
          RUST_BACKTRACE: "1"
        run: |
          cargo test --release


  build:
    name: build
    runs-on: ubuntu-22.04
    needs: [ prepare, check ]
    if: needs.prepare.outputs.do-build == 'true'
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fixup Dockerfile for Podman 3.x
        run: |
          sed -i '/^    --mount/d' Dockerfile
          cat Dockerfile

      - name: Run build
        run: |
          make build-images

      - name: Save images
        run: |
          make save-images

      - name: Upload images
        uses: actions/upload-artifact@v3
        with:
          name: container-images
          path: build/images/all.tar
          if-no-files-found: error


  server-linux:
    runs-on: ubuntu-22.04
    needs: [ prepare, check ]
    if: needs.prepare.outputs.do-build == 'true'
    env:
      VERSION: ${{needs.prepare.outputs.version}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-server-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential curl tzdata libssl-dev pkg-config libsasl2-dev librdkafka-dev libpq-dev libpqxx-dev

      - name: Build binary
        run: |
          PQ_LIB_STATIC=1 SASL2_STATIC=1 OPENSSL_STATIC=1 cargo build --release --features static -p drogue-doppelgaenger-server

      - name: Upload server binary
        uses: actions/upload-artifact@v3
        with:
          name: drogue-doppelgaenger-server-linux-amd64
          path: target/release/drogue-doppelgaenger-server
          if-no-files-found: error

  server-linux-aarch64:
    runs-on: [ self-hosted, linux, ARM64 ]
    needs: [ prepare, check ]
    if: (needs.prepare.outputs.do-build == 'true') && (needs.prepare.outputs.do-publish == 'true') && (needs.prepare.outputs.release == 'true' || github.event.inputs.aarch64 == 'true')
    env:
      VERSION: ${{needs.prepare.outputs.version}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-linux-aarch64-cargo-server-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binary
        run: |
          PQ_LIB_STATIC=1 SASL2_STATIC=1 OPENSSL_STATIC=1 cargo build --release --features static -p drogue-doppelgaenger-server

      - name: Upload server binary
        uses: actions/upload-artifact@v3
        with:
          name: drogue-doppelgaenger-server-linux-aarch64
          path: target/release/drogue-doppelgaenger-server
          if-no-files-found: error

  server-macos:
    runs-on: macos-12
    needs: [ prepare, check ]
    if: needs.prepare.outputs.do-build == 'true'
    env:
      VERSION: ${{needs.prepare.outputs.version}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-server-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          brew update
          brew install librdkafka openssl

      - name: Build postgres dependency
        shell: bash
        run: |
          curl -fsSL -o postgresql-11.13.tar.gz https://ftp.postgresql.org/pub/source/v11.13/postgresql-11.13.tar.gz
          tar xvf postgresql-11.13.tar.gz
          cd postgresql-11.13
          ./configure --prefix=$PWD/../libpq
          make -j
          make install
          cd ..

      - name: Build binary
        shell: bash
        run: |
          PQ_LIB_STATIC=1 PQ_LIB_DIR=$PWD/libpq/lib SASL2_STATIC=1 OPENSSL_STATIC=1 OPENSSL_DIR=/usr/local/opt/openssl DEP_OPENSSL_DIR=/usr/local/opt/openssl RUSTFLAGS="-C target-feature=+crt-static" cargo build --release -p drogue-doppelgaenger-server --features static

      - name: Upload server binary
        uses: actions/upload-artifact@v3
        with:
          name: drogue-doppelgaenger-server-macos-amd64
          path: target/release/drogue-doppelgaenger-server
          if-no-files-found: error


  deploy:
    name: deploy on kind
    runs-on: ubuntu-22.04
    needs: [ prepare, build ]
    if: needs.prepare.outputs.do-build == 'true'
    env:
      CLUSTER: "kind"
      # both podman or docker works, but we must use it consistently, and kind uses docker
      CONTAINER: "docker"

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.VERSION_HELM }}

      - name: Fetch container images
        uses: actions/download-artifact@v3
        with:
          name: container-images

      - name: Create k8s kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          wait: 300s
          cluster_name: kind
          config: deploy/kind/cluster-config.yaml
          version: v0.16.0

      - name: Load images
        run: ${CONTAINER} load -i all.tar

      - name: Tag images
        run: |
          make tag-images CONTAINER_REGISTRY=dev.local IMAGE_TAG=${{ github.sha }}

      - name: Load images in kind
        run: make kind-load CONTAINER_REGISTRY=dev.local IMAGE_TAG=${{ github.sha }}

      - name: Delete loaded images
        run: rm all.tar

      - name: List all images in kind
        run: ${CONTAINER} exec -t kind-control-plane crictl images

      - name: Deploy
        env:
          DEBUG: "true"
        run: |
          ./scripts/drgadm deploy \
            -s drogueCloudTwin.defaults.images.repository=dev.local \
            -S drogueCloudTwin.defaults.images.tag=${{ github.sha }} \
            -s drogueCloudTwin.defaults.images.pullPolicy=Never
        timeout-minutes: 30

      - name: Collect logs
        if: failure()
        run: |
          mkdir -p /tmp/logs/kind
          kind export logs /tmp/logs/kind
          mkdir -p /tmp/logs/ns
          for ns in kafka drogue-doppelgaenger; do
            ./.github/scripts/collect_logs.sh /tmp/logs/ns/$ns $ns
          done

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: deploy-logs
          path: /tmp/logs

  publish:
    needs: [ prepare, deploy, test, server-linux, server-macos ]
    if: (needs.prepare.outputs.do-build == 'true') && (needs.prepare.outputs.do-publish == 'true')

    runs-on: ubuntu-22.04

    env:
      CONTAINER_REGISTRY: ghcr.io/${{ github.repository_owner }}
      VERSION: ${{needs.prepare.outputs.version}}

    steps:

      - name: Dump state
        run: |
          echo "Tag/version: ${VERSION} / ${{needs.prepare.outputs.version}}"
          echo "Should we publish artifacts? - do-publish = ${{needs.prepare.outputs.do-publish}}"
          echo "Release? - release = ${{needs.prepare.outputs.release}}"
          echo "Pre-release? - prerelease = ${{needs.prepare.outputs.prerelease}}"

      # Start the actual build

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fetch container images
        uses: actions/download-artifact@v3
        with:
          name: container-images

      - name: Fetch static server binary (linux-amd64)
        uses: actions/download-artifact@v3
        if: needs.prepare.outputs.release
        with:
          name: drogue-doppelgaenger-server-linux-amd64
          path: drogue-doppelgaenger-server-linux-amd64

      - name: Fetch static server binary (macos-amd64)
        uses: actions/download-artifact@v3
        if: needs.prepare.outputs.release
        with:
          name: drogue-doppelgaenger-server-macos-amd64
          path: drogue-doppelgaenger-server-macos-amd64

      - name: Fetch static server binary (linux-aarch64)
        uses: actions/download-artifact@v3
        if: needs.prepare.outputs.release
        with:
          name: drogue-doppelgaenger-server-linux-aarch64
          path: drogue-doppelgaenger-server-linux-aarch64

      - name: Rename static server binaries
        if: needs.prepare.outputs.release
        run: |
          mkdir server-binaries
          mv drogue-doppelgaenger-server-linux-amd64/drogue-doppelgaenger-server   server-binaries/drogue-doppelgaenger-server-linux-amd64
          mv drogue-doppelgaenger-server-linux-aarch64/drogue-doppelgaenger-server server-binaries/drogue-doppelgaenger-server-linux-aarch64
          mv drogue-doppelgaenger-server-macos-amd64/drogue-doppelgaenger-server   server-binaries/drogue-doppelgaenger-server-macos-amd64

      - name: Load images in podman
        run: |
          podman load -i all.tar
          podman images

      - name: Login to github container repository
        run: echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag and push images
        run: |
          make tag-images "IMAGE_TAG=$VERSION"
          make push-images "IMAGE_TAG=$VERSION"
          sleep 10 # delay a bit for API rate limiting issues

      - name: Install convco
        if: needs.prepare.outputs.release
        run: |
          curl -fsSL -o convco.zip https://github.com/convco/convco/releases/download/v0.3.11/convco-ubuntu.zip
          unzip convco.zip
          install convco /usr/local/bin

      - name: Generate changelog
        if: needs.prepare.outputs.release
        run: |
          convco changelog --max-versions=1 > /tmp/changelog.md

      - name: Create Release
        if: needs.prepare.outputs.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ needs.prepare.outputs.version }}
        run: |
          OPTS=""
          if [[ "${{ needs.prepare.outputs.prerelease }}" == "true" ]]; then
            OPTS="${OPTS} -p"
          fi
          gh release create $OPTS --title "${{ needs.prepare.outputs.version }}" -F /tmp/changelog.md $TAG $(find server-binaries -type f)
